#!/bin/sh
# Turn std/*.dt into a C data fragment: one { name, source } entry per module.
#
# The .dt files are the source of truth — they are ordinary ducktape and can be
# run directly (`./build/ducktape --run std/cmp.dt`). This only mirrors them
# into the binary so `use std::cmp;` needs no install path.
#
# Each source line becomes its own C string literal; adjacent literals are
# concatenated by the compiler, so the emitted form stays diffable and the
# escaping is one pass over `\` and `"`.
#
# usage: embed_std.sh <std-dir> <out-header>
set -eu

std_dir=$1
out=$2

tmp="$out.tmp"
: > "$tmp"

{
    echo "// generated by scripts/embed_std.sh -- do not edit."
    echo "// regenerate with: make (any std/*.dt change triggers it)"

    for f in "$std_dir"/*.dt; do
        [ -e "$f" ] || continue
        name=$(basename "$f" .dt)
        echo "{\"$name\","
        # escape backslashes first, then quotes, then wrap each line
        sed -e 's/\\/\\\\/g' \
            -e 's/"/\\"/g' \
            -e 's/^/"/' \
            -e 's/$/\\n"/' "$f"
        echo "},"
    done
} > "$tmp"

# only replace the real header when the content changed, so an unchanged std
# doesn't force a rebuild of everything that includes it
if cmp -s "$tmp" "$out" 2>/dev/null; then
    rm -f "$tmp"
else
    mv "$tmp" "$out"
fi
